# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changelog < Formula
  desc "A changelog generator which uses GitHub's API for the details"
  homepage "https://github.com/jimschubert/changelog"
  version "1.2.0"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jimschubert/changelog/releases/download/v1.2.0/changelog_1.2.0_Darwin_x86_64.tar.gz"
    sha256 "78b70fb58519610359236589ced161aa58766475811622ef6c440df41bcaec07"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jimschubert/changelog/releases/download/v1.2.0/changelog_1.2.0_Linux_x86_64.tar.gz"
    sha256 "570ab2edd418283c6b0403743c5e066acdb1911818df53ffb2349480ce24a811"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/jimschubert/changelog/releases/download/v1.2.0/changelog_1.2.0_Linux_armv6.tar.gz"
    sha256 "0f2c99aa4da68691163cfb80b0e44ec12e8c3fcd3a10fd12d3397f2d08fb9566"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jimschubert/changelog/releases/download/v1.2.0/changelog_1.2.0_Linux_arm64.tar.gz"
    sha256 "d635c0d9210297a2c65ee994411cb9d2fa541e44c235ec5304a8043cfc42fca2"
  end

  depends_on "go"

  def install
    bin.install "changelog"
  end

  test do
    system "#{bin}/changelog -v"
  end
end
