# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changelog < Formula
  desc "A changelog generator which uses GitHub's API for the details"
  homepage "https://github.com/jimschubert/changelog"
  version "1.2.1"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jimschubert/changelog/releases/download/v1.2.1/changelog_1.2.1_Darwin_x86_64.tar.gz"
      sha256 "219a9d71de38072cb8d988c9a46c176666b8a9d325f9ec8fcea5576455db7deb"
    end

    depends_on arch: [:x86_64]
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jimschubert/changelog/releases/download/v1.2.1/changelog_1.2.1_Linux_x86_64.tar.gz"
      sha256 "9286a707b1dee18c25293f6b60b4be99a4410465c229f4cebb52bef54d65c194"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jimschubert/changelog/releases/download/v1.2.1/changelog_1.2.1_Linux_armv6.tar.gz"
      sha256 "a86ea0f9f225e5aa9b0c755a8fb8c64c951bbf83e8ccdaa48e111449fa83b0b4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimschubert/changelog/releases/download/v1.2.1/changelog_1.2.1_Linux_arm64.tar.gz"
      sha256 "b6e530dd5a9fdb64bbfa25ee766b83e2b6d1134a11fd9daf0b7cdc05bab954e1"
    end

    depends_on arch: [:x86_64, :aarch64, :arm]
  end

  depends_on "go"

  def install
    bin.install "changelog"
  end

  test do
    system "#{bin}/changelog -v"
  end
end
