# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docked < Formula
  desc "A Dockerfile linter"
  homepage "https://github.com/jimschubert/docked"
  version "0.6.0"
  license "Apache 2.0"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jimschubert/docked/releases/download/v0.6.0/docked_darwin_amd64.tar.gz"
      sha256 "4bc7ecf381845288d72034c078dc60f14ab0de594dc1d3f46fc8498bd59d5086"

      def install
        bin.install "docked"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jimschubert/docked/releases/download/v0.6.0/docked_darwin_arm64.tar.gz"
      sha256 "540da7b63e1c58d30f95d7e13cfbbddde958aa5c6b93040564ba6ae4ff5d216e"

      def install
        bin.install "docked"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jimschubert/docked/releases/download/v0.6.0/docked_linux_amd64.tar.gz"
      sha256 "8e8f5e8140e8843eb5ac22cadee8bb0864d87f889c108523579084739b5153a1"
      def install
        bin.install "docked"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/jimschubert/docked/releases/download/v0.6.0/docked_linux_armv6.tar.gz"
      sha256 "14c812ecaf67e103aaf67ed016abbb28eb231d9439cc36728ba0be3452ceb744"
      def install
        bin.install "docked"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jimschubert/docked/releases/download/v0.6.0/docked_linux_arm64.tar.gz"
      sha256 "4987a5cdc7f18add7e315b416725fd4be77b9ff9cf66fbab724f58fa2e2860f4"
      def install
        bin.install "docked"
      end
    end
  end

  test do
    system "#{bin}/docked -v"
  end
end
