# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yizzy < Formula
  desc "YAML migrations."
  homepage "https://github.com/jimschubert/yizzy"
  version "0.1"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jimschubert/yizzy/releases/download/v0.1/yizzy_0.1_Darwin_x86_64.tar.gz"
    sha256 "df6b0e46676c1fc5a2583e27d4afbe403ae38a5c794ad36b32a0f842877dd0bf"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jimschubert/yizzy/releases/download/v0.1/yizzy_0.1_Darwin_arm64.tar.gz"
    sha256 "2543cd35aa1e27a55e2164dd19d1ddb966e350c137f20239396d4f528d5c2d8a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jimschubert/yizzy/releases/download/v0.1/yizzy_0.1_Linux_x86_64.tar.gz"
    sha256 "d88eccf728f35054b40a69e271d817a41f6631d275c702dcd80c2d82816fa839"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/jimschubert/yizzy/releases/download/v0.1/yizzy_0.1_Linux_armv6.tar.gz"
    sha256 "455807a14c2494af36e33332e85ea73043c69f03701c6ccc518d20eb3c0445d0"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jimschubert/yizzy/releases/download/v0.1/yizzy_0.1_Linux_arm64.tar.gz"
    sha256 "e1f52caa41d570bbe6f5396b3cb32c42817f46a389f06ebb06ba63b4c041d140"
  end

  depends_on "go"

  def install
    bin.install "yizzy"
  end

  test do
    system "#{bin}/yizzy -v"
  end
end
